// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6VpAQ0ucGrUYXAPp2tEPF2iRZ6RF4EbI',
    appId: '1:607600602186:web:453cf1f015a12cc7760ab3',
    messagingSenderId: '607600602186',
    projectId: 'chat-app-21901',
    authDomain: 'chat-app-21901.firebaseapp.com',
    storageBucket: 'chat-app-21901.appspot.com',
    measurementId: 'G-8LG88RND3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPDBlEoCvUYyauiVh8UPmqh3w4iH-iHoE',
    appId: '1:607600602186:android:58d1a706cff9b1ba760ab3',
    messagingSenderId: '607600602186',
    projectId: 'chat-app-21901',
    storageBucket: 'chat-app-21901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpTUtl-LYEap7RWhacdYmXlaVTtHrUYjc',
    appId: '1:607600602186:ios:f7e6facb7c429f43760ab3',
    messagingSenderId: '607600602186',
    projectId: 'chat-app-21901',
    storageBucket: 'chat-app-21901.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpTUtl-LYEap7RWhacdYmXlaVTtHrUYjc',
    appId: '1:607600602186:ios:f7e6facb7c429f43760ab3',
    messagingSenderId: '607600602186',
    projectId: 'chat-app-21901',
    storageBucket: 'chat-app-21901.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6VpAQ0ucGrUYXAPp2tEPF2iRZ6RF4EbI',
    appId: '1:607600602186:web:310741a0dd2a9aca760ab3',
    messagingSenderId: '607600602186',
    projectId: 'chat-app-21901',
    authDomain: 'chat-app-21901.firebaseapp.com',
    storageBucket: 'chat-app-21901.appspot.com',
    measurementId: 'G-J3Q4MPBE26',
  );
}
